[package]
name = "gta_game"
version = "0.1.0"
edition = "2024"

[features]
default = []
debug-movement = []
debug-audio = []
debug-ui = []
debug-timing = []

[[bin]]
name = "gta_simple"
path = "src/main_simple.rs"

[dependencies]
bevy = { version = "0.16.1", features = ["serialize", "shader_format_glsl"] }
bevy_rapier3d = "0.30.0"
bytemuck = { version = "1.18", features = ["derive"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
chrono = { version = "0.4", features = ["serde"] }
