[workspace]
members = [
    "crates/*",
    "examples",
    "tools/xtask",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.77"
version = "0.1.0"
authors = ["Brady Jeong <bradyjeong@Mac.attlocal.net>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/bradyjeong/bevy-gta-clone"

[workspace.dependencies]
# Core dependencies
anyhow = { version = "1.0", default-features = false }
glam = { version = "0.25", features = ["fast-math"] }
wgpu = { version = "0.19" }
winit = { version = "0.29", default-features = false, features = ["x11", "rwh_06"] }
rapier3d = "0.18"
bevy_ecs = "0.13"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"
bitset-fixed = "0.1"
pollster = "0.3"

# Configuration
ron = "0.8"
dirs = "5.0"

# Dev tools
rstest = "0.18"
criterion = "0.5"
tempfile = "3.0"

[package]
name = "gta_game"
edition = "2021"
version = "0.1.0"
authors = ["Brady Jeong <bradyjeong@Mac.attlocal.net>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/bradyjeong/bevy-gta-clone"

[dependencies]
gameplay_factory = { path = "crates/gameplay_factory" }
config_core = { path = "crates/config_core" }
env_logger = "0.11"

[[bin]]
name = "prefab-ls"
path = "src/bin/prefab-ls.rs"

[[bin]]
name = "collision_test"
path = "collision_test.rs"
