[workspace]
resolver = "2"
members = [
    "game_core",
    "game_bin",
    "engine_core", 
    "engine_bevy",
    "gameplay_sim",
    "gameplay_render",
    "gameplay_ui",
    "test_utils",
    "tests"
]

[workspace.features]
default = []
# Development and debugging features
debug-movement = []
debug-audio = []
debug-ui = []
# Experimental features for AI development
experimental = []
# Testing and golden frame features
golden-frames = []
# GPU compute features
gpu-culling = []
default-members = [
    "game_bin",
    "engine_core", 
    "engine_bevy",
    "game_core",
    "gameplay_sim",
    "gameplay_render",
    "gameplay_ui"
]



[workspace.dependencies]
bevy = { version = "0.16.1", features = ["serialize", "shader_format_glsl"] }
bevy_rapier3d = "0.30.0"
bytemuck = { version = "1.18", features = ["derive"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
chrono = { version = "0.4", features = ["serde"] }
image = "0.24"



[workspace.metadata.docs.rs]
all-features = true
