[workspace]
members = [
    "crates/*",
    "tools/xtask",
]
exclude = [
    "examples",  # Will re-enable during migration per Oracle's plan
]
resolver = "2"

# STRATEGIC SHIFT: Updated to Rust 2024 edition (released with 1.85.0)
# Current: bevy_ecs 0.13 + micro-crates  
# Target: Bevy 0.16.1 + strategic modularity
[workspace.package]
edition = "2024" 
rust-version = "1.85"
version = "0.1.0"
authors = ["Brady Jeong <bradyjeong@Mac.attlocal.net>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/bradyjeong/bevy-gta-clone"

[workspace.dependencies]
# ORACLE'S VERSION-CONSISTENCY STRATEGY: Single source of truth for all versions
# ---------- Bevy core ----------
bevy = "=0.16.1"                          # Full engine, patch-locked
bevy_rapier3d = "=0.26.0"                 # Compiled against Bevy 0.16.1
# ---------- Rendering ----------
# Bevy re-exports wgpu/winit; keep them in sync for crates that still need them
wgpu = "26.0.0"   # Updated to current version
winit = "0.30.0"  # Current version
# ---------- Math / util ----------
glam = { version = "^0.28", features = ["fast-math"] }
serde = { version = "^1", features = ["derive"] }
anyhow = { version = "^1.0", default-features = false }
thiserror = { version = "^1.0" }
bitset-fixed = "^0.1"
pollster = "^0.3"

# Configuration
ron = "^0.8"
dirs = "^5.0"

# Dev tools
rstest = "^0.18"
criterion = "^0.5"
tempfile = "^3.0"

# LEGACY: Will be removed in Phase 2
bevy_ecs = "0.13"
rapier3d = "0.18"

# Ensure all crates use the exact wgpu/winit Bevy expects
# Note: Patches removed temporarily for baseline capture

[package]
name = "gta_game"
edition = "2024"
version = "0.1.0"
authors = ["Brady Jeong <bradyjeong@Mac.attlocal.net>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/bradyjeong/bevy-gta-clone"

# Disable automatic example discovery
autoexamples = false

[features]
default = []
ron = ["gameplay_factory/ron"]

[dependencies]
gameplay_factory = { path = "crates/gameplay_factory" }
config_core = { path = "crates/config_core" }
env_logger = "0.11"

[[bin]]
name = "prefab-ls"
path = "src/bin/prefab-ls.rs"

[[bin]]
name = "collision_test"
path = "collision_test.rs"
