[workspace]
resolver = "2"
members = [
    "game_core",
    "game_bin",
    "engine_core", 
    "engine_bevy",
    "gameplay_sim",
    "gameplay_render",
    "gameplay_ui",
    "test_utils",
    "tests"
]
default-members = [
    "game_bin",
    "engine_core", 
    "engine_bevy",
    "game_core",
    "gameplay_sim",
    "gameplay_render",
    "gameplay_ui"
]

# The legacy monolith as a library package
[package]
name = "gta_game_legacy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_rapier3d = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
chrono = { workspace = true }

# Internal dependencies
game_core = { path = "game_core" }
engine_core = { path = "engine_core" }
engine_bevy = { path = "engine_bevy" }
gameplay_sim = { path = "gameplay_sim" }
gameplay_render = { path = "gameplay_render" }
gameplay_ui = { path = "gameplay_ui" }

[features]
default = []

[workspace.dependencies]
bevy = { version = "0.16.1", features = ["serialize", "shader_format_glsl"] }
bevy_rapier3d = "0.30.0"
bytemuck = { version = "1.18", features = ["derive"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
chrono = { version = "0.4", features = ["serde"] }
image = "0.24"

[dev-dependencies]
# bevy_frame_capture = "0.2"  # Not available, using manual approach

[workspace.metadata.docs.rs]
all-features = true
