[package]
name = "engine_core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
ron = { workspace = true }
rand = { workspace = true }
# Pure math and utilities - no Bevy dependencies
