[package]
name = "perf_test"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
bevy = { version = "=0.16.1", features = ["bevy_winit", "bevy_render"] }
clap = { version = "4.4", features = ["derive"] }
rayon = "1.8"
slotmap = "1.0"
