[package]
name = "engine_bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_rapier3d = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }

# Internal dependencies
engine_core = { path = "../engine_core" }
