name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

# Granular permissions for GitHub Pages deployment
permissions:
  contents: read          # Read repository contents
  pages: write           # Write to GitHub Pages
  id-token: write        # Write ID tokens for OIDC authentication
  actions: read          # Read GitHub Actions
  checks: write          # Write check runs
  deployments: write     # Write deployment statuses
  statuses: write        # Write commit statuses

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      
    - name: Generate documentation
      run: |
        RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --all-features
        
    - name: Create index.html
      run: |
        cat > target/doc/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>AMP Game Engine Documentation</title>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0; url=amp_core/index.html">
        </head>
        <body>
            <h1>AMP Game Engine Documentation</h1>
            <p>Redirecting to <a href="amp_core/index.html">amp_core documentation</a>...</p>
            <h2>Available Crates:</h2>
            <ul>
                <li><a href="amp_core/index.html">amp_core</a> - Core error handling and utilities</li>
                <li><a href="amp_math/index.html">amp_math</a> - Spatial mathematics and Morton encoding</li>
                <li><a href="amp_spatial/index.html">amp_spatial</a> - Hierarchical spatial partitioning</li>
                <li><a href="amp_gpu/index.html">amp_gpu</a> - GPU abstraction over wgpu</li>
                <li><a href="amp_world/index.html">amp_world</a> - ECS world management</li>
                <li><a href="config_core/index.html">config_core</a> - Configuration system</li>
            </ul>
        </body>
        </html>
        EOF
        
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./target/doc
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4
