name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

# Granular permissions for GitHub Pages deployment
permissions:
  contents: read          # Read repository contents
  pages: write           # Write to GitHub Pages
  id-token: write        # Write ID tokens for OIDC authentication
  actions: read          # Read GitHub Actions
  checks: write          # Write check runs
  deployments: write     # Write deployment statuses
  statuses: write        # Write commit statuses

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      
    - name: Generate documentation
      run: |
        RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --all-features
        
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./target/doc
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4
